apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: inventory
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  # Change these to secure random values in production
  postgres-password: "inventorydb123"
  postgres-user: "inventory"
  postgres-db: "inventorydb"
