apiVersion: v1
kind: Secret
metadata:
  name: inventory-secret
  namespace: inventory
  annotations:
    argocd.argoproj.io/sync-wave: "2"
type: Opaque
stringData:
  # Change this to a secure random value in production
  secret-key: "django-insecure-xfu-vv2sc_9x!8yg&$j43md9yhux6ibzh*ku23&61h=x54durh"
