apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-processor
  namespace: image-processor
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: image-processor
  template:
    metadata:
      labels:
        app: image-processor
    spec:
      containers:
      - name: image-processor
        image: ghcr.io/marcoplaisier/image-processor:latest
        ports:
        - containerPort: 5000