apiVersion: v1
kind: Service
metadata:
  name: image-processor-service
  namespace: image-processor
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  selector:
    app: image-processor
  ports:
    - port: 80
      targetPort: 5000
  type: ClusterIP