apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: karavan-ingress
  namespace: karavan
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  rules:
    - host: karavan.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: karavan-service
                port:
                  number: 80
