apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: karavan-role-binding
  namespace: karavan
  annotations:
    argocd.argoproj.io/sync-wave: "2"
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: karavan
subjects:
- kind: ServiceAccount
  apiGroup: ""
  name: karavan
  namespace: karavan
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: karavan-cluster-role-binding
  namespace: karavan
  annotations:
    argocd.argoproj.io/sync-wave: "2"
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: view
subjects:
- kind: ServiceAccount
  apiGroup: ""
  name: karavan
  namespace: karavan
