apiVersion: v1
kind: Service
metadata:
  name: karavan-service
  namespace: karavan
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  selector:
    app: karavan
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
